### ISSUE TITLE
Consider to use Yarn 

### ISSUE THREAD

**Issue by blobor** [Julianitta/weather-app#2]
Checkout Yarn package manager https://yarnpkg.com/en/

**Comment by Julianitta** [comment]
https://github.com/Julianitta/weather-app/commit/21d012399dd3cb3ddb98a9d1751876fdd2cefbe9
https://github.com/Julianitta/weather-app/commit/27f95faa1045a112111895a1f856e1cbe9064c35
https://github.com/Julianitta/weather-app/commit/7d81b39efb5d4a229d7fe314c33457663c4142d1

**Comment by blobor** [comment]
Probably you could add some text here with urls to commits, instead of just ulrs
