### ISSUE TITLE
Use snazzy package for proper formatting of listing errors 

### ISSUE THREAD

**Issue by blobor** [Julianitta/weather-app#3]

**Comment by Julianitta** [comment]
Done,
https://github.com/Julianitta/weather-app/commit/66c3572574f1714b32f9b070feceeb65e8649fd0

**Comment by blobor** [comment]
Do we need this `|| exit 0`?

**Comment by Julianitta** [comment]
Well, it still returns dirty log after

**Comment by blobor** [comment]
Maybe its because linting errors?

**Comment by blobor** [comment]
Could you please provide this logs?

**Comment by Julianitta** [comment]
After the linting errors, there is the following:


npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "lint"
npm ERR! node v7.3.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! forecast@1.0.0 lint: `standard --verbose | snazzy`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the forecast@1.0.0 lint script 'standard --verbose | snazzy'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the forecast package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     standard --verbose | snazzy
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs forecast
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls forecast
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\pet-projects\weather-app\npm-debug.log

**Comment by blobor** [comment]
Could you try to run it with `yarn`?
Just install yarn with `npm i -g yarn`
And after, rub `yarn lint`

**Comment by Julianitta** [comment]
Yes, I did it already. With yarn it works great.
Can I consider yarn as a solution to this issue?

**Comment by blobor** [comment]
I think it fine for now, but in that case update `README.md` file with instructions.

**Comment by Julianitta** [comment]
https://github.com/Julianitta/weather-app/commit/27f95faa1045a112111895a1f856e1cbe9064c35
